### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler:

### ISSUE THREAD

**Issue by MaxenceChantome-Fox** [Netvent/appsamurai-adsdk-ios#1]
Hi, I'm trying to use your SDK installed via pods in an iOS app but I encounter this error `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler` when I try to import `ASAttributionSDK`

I'm using the lastest xcode version: xcode 11.0.
Is it possible to update the sdk?

Thank you !

**Comment by yigcal** [comment]
Hi @MaxenceChantome-Fox ,

Thanks for letting us know. We have updated the SDK based on your problem. 

If you face any other problems, please let us know from the following repositories:
- ios: https://github.com/Netvent/as-attribution-ios 
- android: https://github.com/Netvent/as-attribution-android

Cheers
